server:
  port: 8080

# 单数据源的配置
#spring:
#  application:
#    version: ${random.long}
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.4.18:5432/gang
#    username: postgres
#    password: postgres

spring:
  application:
    version: ${random.long}

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

#   无法保证事务
  datasource:
    primary:
      jdbc-url: jdbc:postgresql://192.168.4.38:5431/gang
      username: postgres
      password: postgres
      type: org.postgresql.Driver
    secondary:
      jdbc-url: jdbc:postgresql://192.168.4.38:5431/lg
      username: postgres
      password: postgres
      type: org.postgresql.Driver

#不知到 mysql  怎么配置  https://www.bilibili.com/video/av62047875/?p=23
#primarydb:
#  uniqueResourceName: primary
#  xaDataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlXADataSource





swagger:
  enabled: true
  title: 开发文档
  version: ${spring.application.version}
  description: 开发文档
  exclude-path: /error,/actuator/**
  contact:
    name: CoderLG
    email: im.lg@qq.com
